// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Demo.IntegrationTests.ApiClient.BodyParameter.ObjectNamespace.Item;
using ReQuesty.Demo.IntegrationTests.ApiClient.Models;
using ReQuesty.Runtime.Abstractions.Serialization;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ReQuesty.Demo.IntegrationTests.ApiClient.BodyParameter.ObjectNamespace
{
    /// <summary>
    /// Builds and executes requests for operations under \BodyParameter\object
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.6")]
    public partial class ObjectRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the ReQuesty.Demo.IntegrationTests.ApiClient.BodyParameter.object.item collection</summary>
        /// <param name="position">The ID of the object to replace.</param>
        /// <returns>A <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.BodyParameter.ObjectNamespace.Item.ObjectItemRequestBuilder"/></returns>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.BodyParameter.ObjectNamespace.Item.ObjectItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::ReQuesty.Demo.IntegrationTests.ApiClient.BodyParameter.ObjectNamespace.Item.ObjectItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.BodyParameter.ObjectNamespace.ObjectRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ObjectRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/BodyParameter/object", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.BodyParameter.ObjectNamespace.ObjectRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ObjectRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/BodyParameter/object", rawUrl)
        {
        }
        /// <summary>
        /// Accepts a SomeObject body and returns it with 201 Created.
        /// </summary>
        /// <returns>A <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.SomeObject"/></returns>
        /// <param name="body">A sample object model to be used in the demo API</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        public async Task<global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.SomeObject?> PostAsync(global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.SomeObject body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
            ArgumentNullException.ThrowIfNull(body);
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.SomeObject>(requestInfo, global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.SomeObject.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Accepts a SomeObject body and returns it with 201 Created.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">A sample object model to be used in the demo API</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        public RequestInformation ToPostRequestInformation(global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.SomeObject body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
            ArgumentNullException.ThrowIfNull(body);
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.BodyParameter.ObjectNamespace.ObjectRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.BodyParameter.ObjectNamespace.ObjectRequestBuilder WithUrl(string rawUrl)
        {
            return new global::ReQuesty.Demo.IntegrationTests.ApiClient.BodyParameter.ObjectNamespace.ObjectRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#nullable restore
#pragma warning restore CS0618
