// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Demo.IntegrationTests.ApiClient.StatusCode.Badrequest;
using ReQuesty.Demo.IntegrationTests.ApiClient.StatusCode.Created;
using ReQuesty.Demo.IntegrationTests.ApiClient.StatusCode.Internalerror;
using ReQuesty.Demo.IntegrationTests.ApiClient.StatusCode.Nocontent;
using ReQuesty.Demo.IntegrationTests.ApiClient.StatusCode.Notfound;
using ReQuesty.Demo.IntegrationTests.ApiClient.StatusCode.Ok;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ReQuesty.Demo.IntegrationTests.ApiClient.StatusCode
{
    /// <summary>
    /// Builds and executes requests for operations under \StatusCode
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.6")]
    public partial class StatusCodeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The badrequest property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.StatusCode.Badrequest.BadrequestRequestBuilder Badrequest
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.StatusCode.Badrequest.BadrequestRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The created property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.StatusCode.Created.CreatedRequestBuilder Created
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.StatusCode.Created.CreatedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The internalerror property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.StatusCode.Internalerror.InternalerrorRequestBuilder Internalerror
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.StatusCode.Internalerror.InternalerrorRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The nocontent property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.StatusCode.Nocontent.NocontentRequestBuilder Nocontent
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.StatusCode.Nocontent.NocontentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The notfound property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.StatusCode.Notfound.NotfoundRequestBuilder Notfound
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.StatusCode.Notfound.NotfoundRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ok property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.StatusCode.Ok.OkRequestBuilder Ok
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.StatusCode.Ok.OkRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.StatusCode.StatusCodeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StatusCodeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/StatusCode", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.StatusCode.StatusCodeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StatusCodeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/StatusCode", rawUrl)
        {
        }
    }
}
#nullable restore
#pragma warning restore CS0618
