---
version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: daily
    groups:
      nuget:
        patterns:
          - "*"
    ignore:
      - dependency-name: "Microsoft.CodeAnalysis.CSharp"
      - dependency-name: "Microsoft.CodeAnalysis.Analyzers"
      - dependency-name: "System.CommandLine"
      - dependency-name: "System.CommandLine.Hosting"
      - dependency-name: "System.CommandLine.Rendering"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    groups:
      actions:
        patterns:
          - "*"