// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using ReQuesty.Runtime.Serialization.Form;
using ReQuesty.Runtime.Serialization.Json;
using ReQuesty.Runtime.Serialization.Multipart;
using ReQuesty.Runtime.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ReQuesty.Demo.IntegrationTests.ApiClient
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.5")]
    public partial class DemoApiClient : BaseRequestBuilder
    {
        /// <summary>The PrimativeReturn property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.PrimativeReturnRequestBuilder PrimativeReturn
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.PrimativeReturnRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.DemoApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DemoApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
        }
    }
}
#nullable restore
#pragma warning restore CS0618
