// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Demo.IntegrationTests.ApiClient.BodyParameter;
using ReQuesty.Demo.IntegrationTests.ApiClient.CollectionReturn;
using ReQuesty.Demo.IntegrationTests.ApiClient.EnumReturn;
using ReQuesty.Demo.IntegrationTests.ApiClient.ObjectReturn;
using ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter;
using ReQuesty.Demo.IntegrationTests.ApiClient.Polymorphic;
using ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn;
using ReQuesty.Demo.IntegrationTests.ApiClient.QueryParameter;
using ReQuesty.Demo.IntegrationTests.ApiClient.StatusCode;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using ReQuesty.Runtime.Serialization.Form;
using ReQuesty.Runtime.Serialization.Json;
using ReQuesty.Runtime.Serialization.Multipart;
using ReQuesty.Runtime.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ReQuesty.Demo.IntegrationTests.ApiClient
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.6")]
    public partial class DemoApiClient : BaseRequestBuilder
    {
        /// <summary>The BodyParameter property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.BodyParameter.BodyParameterRequestBuilder BodyParameter
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.BodyParameter.BodyParameterRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The CollectionReturn property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.CollectionReturn.CollectionReturnRequestBuilder CollectionReturn
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.CollectionReturn.CollectionReturnRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The EnumReturn property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.EnumReturn.EnumReturnRequestBuilder EnumReturn
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.EnumReturn.EnumReturnRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ObjectReturn property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.ObjectReturn.ObjectReturnRequestBuilder ObjectReturn
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.ObjectReturn.ObjectReturnRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The PathParameter property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.PathParameterRequestBuilder PathParameter
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.PathParameterRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Polymorphic property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.Polymorphic.PolymorphicRequestBuilder Polymorphic
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.Polymorphic.PolymorphicRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The PrimativeReturn property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.PrimativeReturnRequestBuilder PrimativeReturn
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.PrimativeReturnRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The QueryParameter property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.QueryParameter.QueryParameterRequestBuilder QueryParameter
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.QueryParameter.QueryParameterRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The StatusCode property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.StatusCode.StatusCodeRequestBuilder StatusCode
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.StatusCode.StatusCodeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.DemoApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DemoApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
        }
    }
}
#nullable restore
#pragma warning restore CS0618
