// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Demo.IntegrationTests.ApiClient.Polymorphic.Animal;
using ReQuesty.Demo.IntegrationTests.ApiClient.Polymorphic.Dog;
using ReQuesty.Demo.IntegrationTests.ApiClient.Polymorphic.DogAnimal;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ReQuesty.Demo.IntegrationTests.ApiClient.Polymorphic
{
    /// <summary>
    /// Builds and executes requests for operations under \Polymorphic
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.6")]
    public partial class PolymorphicRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The animal property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.Polymorphic.Animal.AnimalRequestBuilder Animal
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.Polymorphic.Animal.AnimalRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The dog property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.Polymorphic.Dog.DogRequestBuilder Dog
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.Polymorphic.Dog.DogRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The dogAnimal property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.Polymorphic.DogAnimal.DogAnimalRequestBuilder DogAnimal
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.Polymorphic.DogAnimal.DogAnimalRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.Polymorphic.PolymorphicRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PolymorphicRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Polymorphic", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.Polymorphic.PolymorphicRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PolymorphicRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Polymorphic", rawUrl)
        {
        }
    }
}
#nullable restore
#pragma warning restore CS0618
