// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.LongId.Item;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.LongId
{
    /// <summary>
    /// Builds and executes requests for operations under \PathParameter\longId
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.6")]
    public partial class LongIdRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.longId.item collection</summary>
        /// <param name="position">The long ID.</param>
        /// <returns>A <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.LongId.Item.WithLongItemRequestBuilder"/></returns>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.LongId.Item.WithLongItemRequestBuilder this[long position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("longId", position);
                return new global::ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.LongId.Item.WithLongItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.LongId.LongIdRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LongIdRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/PathParameter/longId", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.LongId.LongIdRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LongIdRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/PathParameter/longId", rawUrl)
        {
        }
    }
}
#nullable restore
#pragma warning restore CS0618
