// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Demo.IntegrationTests.ApiClient.Models;
using ReQuesty.Demo.IntegrationTests.ApiClient.Polymorphic.Animal.Bulk;
using ReQuesty.Runtime.Abstractions.Serialization;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ReQuesty.Demo.IntegrationTests.ApiClient.Polymorphic.Animal
{
    /// <summary>
    /// Builds and executes requests for operations under \Polymorphic\animal
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.6")]
    public partial class AnimalRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The bulk property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.Polymorphic.Animal.Bulk.BulkRequestBuilder Bulk
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.Polymorphic.Animal.Bulk.BulkRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.Polymorphic.Animal.AnimalRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AnimalRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Polymorphic/animal", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.Polymorphic.Animal.AnimalRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AnimalRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Polymorphic/animal", rawUrl)
        {
        }
        /// <summary>
        /// Accepts an AnimalBase body and echoes it back, verifying polymorphic round-trip.
        /// </summary>
        /// <returns>A <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.AnimalBase"/></returns>
        /// <param name="body">The base record for all animal types</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        public async Task<global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.AnimalBase?> PostAsync(global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.AnimalBase body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
            ArgumentNullException.ThrowIfNull(body);
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.AnimalBase>(requestInfo, global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.AnimalBase.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Accepts an AnimalBase body and echoes it back, verifying polymorphic round-trip.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The base record for all animal types</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        public RequestInformation ToPostRequestInformation(global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.AnimalBase body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
            ArgumentNullException.ThrowIfNull(body);
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.Polymorphic.Animal.AnimalRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.Polymorphic.Animal.AnimalRequestBuilder WithUrl(string rawUrl)
        {
            return new global::ReQuesty.Demo.IntegrationTests.ApiClient.Polymorphic.Animal.AnimalRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#nullable restore
#pragma warning restore CS0618
