// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Runtime.Abstractions.Serialization;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System;
namespace ReQuesty.Demo.IntegrationTests.ApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.DogBoxer"/>, <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.DogGoldenRetriever"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.6")]
    public partial class Dog : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.DogBoxer"/></summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.DogBoxer DogBoxer { get; set; } = default!;
        /// <summary>Composed type representation for type <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.DogGoldenRetriever"/></summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.DogGoldenRetriever DogGoldenRetriever { get; set; } = default!;
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.Dog"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.Dog CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            ArgumentNullException.ThrowIfNull(parseNode);
            var result = new global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.Dog();
            result.DogBoxer = new global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.DogBoxer();
            result.DogGoldenRetriever = new global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.DogGoldenRetriever();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(DogBoxer is not null || DogGoldenRetriever is not null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(DogBoxer, DogGoldenRetriever);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            ArgumentNullException.ThrowIfNull(writer);
            writer.WriteObjectValue<global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.DogBoxer>(null, DogBoxer, DogGoldenRetriever);
        }
    }
}
#nullable restore
#pragma warning restore CS0618
