// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Runtime.Abstractions.Serialization;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System;
namespace ReQuesty.Demo.IntegrationTests.ApiClient.Models
{
    /// <summary>
    /// A Boxer dog
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.6")]
    public partial class DogBoxer : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; } = default!;
        /// <summary>The age of the animal in years</summary>
        public int AgeYears { get; set; } = default!;
        /// <summary>Whether the Boxer has a brindle coat</summary>
        public bool IsBrindle { get; set; } = default!;
        /// <summary>Whether the dog has been trained</summary>
        public bool IsTrained { get; set; } = default!;
        /// <summary>The name of the animal</summary>
        public string Name { get; set; } = default!;
        /// <summary>The Type property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.DogBoxer_Type? Type { get; set; } = default!;
        /// <summary>
        /// Instantiates a new <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.DogBoxer"/> and sets the default values.
        /// </summary>
        public DogBoxer()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.DogBoxer"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.DogBoxer CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            ArgumentNullException.ThrowIfNull(parseNode);
            return new global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.DogBoxer();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "ageYears", n => { AgeYears = n.GetIntValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'AgeYears'"); } },
                { "isBrindle", n => { IsBrindle = n.GetBoolValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'IsBrindle'"); } },
                { "isTrained", n => { IsTrained = n.GetBoolValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'IsTrained'"); } },
                { "name", n => { Name = n.GetStringValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'Name'"); } },
                { "$type", n => { Type = n.GetEnumValue<global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.DogBoxer_Type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            ArgumentNullException.ThrowIfNull(writer);
            writer.WriteIntValue("ageYears", AgeYears);
            writer.WriteBoolValue("isBrindle", IsBrindle);
            writer.WriteBoolValue("isTrained", IsTrained);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.DogBoxer_Type>("$type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#nullable restore
#pragma warning restore CS0618
