// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ReQuesty.Demo.IntegrationTests.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0")]
    #pragma warning disable CS1591
    public enum DogGoldenRetriever_Type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "GoldenRetriever")]
        #pragma warning disable CS1591
        GoldenRetriever,
        #pragma warning restore CS1591
    }
}
