// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ReQuesty.Demo.IntegrationTests.ApiClient.Models
{
    /// <summary>The type of data to return</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0")]
    public enum ReturnType
    {
        [EnumMember(Value = "Null")]
        #pragma warning disable CS1591
        Null,
        #pragma warning restore CS1591
        [EnumMember(Value = "Random")]
        #pragma warning disable CS1591
        Random,
        #pragma warning restore CS1591
        [EnumMember(Value = "Invalid")]
        #pragma warning disable CS1591
        Invalid,
        #pragma warning restore CS1591
    }
}
