// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Runtime.Abstractions.Serialization;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System;
namespace ReQuesty.Demo.IntegrationTests.ApiClient.Models
{
    /// <summary>
    /// A sample object model to be used in the demo API
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.5")]
    public partial class SomeObject : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; } = default!;
        /// <summary>The age of the object</summary>
        public int Age { get; set; } = default!;
        /// <summary>The cost of the object</summary>
        public double Cost { get; set; } = default!;
        /// <summary>The unique identifier of the object</summary>
        public Guid Id { get; set; } = default!;
        /// <summary>The name of the object</summary>
        public string Name { get; set; } = default!;
        /// <summary>The timestamp of when the object was requested</summary>
        public DateTimeOffset RequestedAt { get; set; } = default!;
        /// <summary>
        /// Instantiates a new <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.SomeObject"/> and sets the default values.
        /// </summary>
        public SomeObject()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.SomeObject"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.SomeObject CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            ArgumentNullException.ThrowIfNull(parseNode);
            return new global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.SomeObject();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "age", n => { Age = n.GetIntValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'Age'"); } },
                { "cost", n => { Cost = n.GetDoubleValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'Cost'"); } },
                { "id", n => { Id = n.GetGuidValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'Id'"); } },
                { "name", n => { Name = n.GetStringValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'Name'"); } },
                { "requestedAt", n => { RequestedAt = n.GetDateTimeOffsetValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'RequestedAt'"); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            ArgumentNullException.ThrowIfNull(writer);
            writer.WriteIntValue("age", Age);
            writer.WriteDoubleValue("cost", Cost);
            writer.WriteGuidValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteDateTimeOffsetValue("requestedAt", RequestedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#nullable restore
#pragma warning restore CS0618
