// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ReQuesty.Demo.IntegrationTests.ApiClient.Models
{
    /// <summary>Example enum with its values as strings</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0")]
    public enum StringValues
    {
        [EnumMember(Value = "North")]
        #pragma warning disable CS1591
        North,
        #pragma warning restore CS1591
        [EnumMember(Value = "East")]
        #pragma warning disable CS1591
        East,
        #pragma warning restore CS1591
        [EnumMember(Value = "South")]
        #pragma warning disable CS1591
        South,
        #pragma warning restore CS1591
        [EnumMember(Value = "West")]
        #pragma warning disable CS1591
        West,
        #pragma warning restore CS1591
    }
}
