using ReQuesty.Builder.CodeDOM;
using ReQuesty.Builder.Writers;
using ReQuesty.Builder.Writers.CSharp;

using Xunit;

namespace ReQuesty.Builder.Tests.Writers.CSharp;
public sealed class CodeClassDeclarationWriterTests : IDisposable
{
    private const string AutoGenerationHeader = "// <auto-generated/>";
    private const string DefaultPath = "./";
    private const string DefaultName = "name";
    private readonly StringWriter tw;
    private readonly LanguageWriter writer;
    private readonly CodeClassDeclarationWriter codeElementWriter;
    private readonly CodeClass parentClass;

    public CodeClassDeclarationWriterTests()
    {
        codeElementWriter = new CodeClassDeclarationWriter(new CSharpConventionService());
        writer = LanguageWriter.GetLanguageWriter(GenerationLanguage.CSharp, DefaultPath, DefaultName);
        tw = new StringWriter();
        writer.SetTextWriter(tw);
        CodeNamespace root = CodeNamespace.InitRootNamespace();
        parentClass = new()
        {
            Name = "parentClass"
        };
        root.AddClass(parentClass);
    }

    public void Dispose()
    {
        tw?.Dispose();
        GC.SuppressFinalize(this);
    }

    [Fact]
    public void WritesAutoGeneratedHeader()
    {
        codeElementWriter.WriteCodeElement(parentClass.StartBlock, writer);
        string result = tw.ToString();
        Assert.Contains(AutoGenerationHeader, result);
    }

    [Fact]
    public void WritesSimpleDeclaration()
    {
        codeElementWriter.WriteCodeElement(parentClass.StartBlock, writer);
        string result = tw.ToString();
        Assert.Contains("public partial class", result);
    }

    [Fact]
    public void WritesWarningDisableCs0618()
    {
        codeElementWriter.WriteCodeElement(parentClass.StartBlock, writer);
        string result = tw.ToString();
        Assert.Contains("#pragma warning disable CS0618", result);
    }

    [Fact]
    public void WritesImplementation()
    {
        ClassDeclaration declaration = parentClass.StartBlock;
        declaration.AddImplements(new CodeType
        {
            Name = "someInterface"
        });
        codeElementWriter.WriteCodeElement(declaration, writer);
        string result = tw.ToString();
        Assert.Contains(":", result);
    }

    [Fact]
    public void WritesInheritance()
    {
        ClassDeclaration declaration = parentClass.StartBlock;
        declaration.Inherits = new()
        {
            Name = "someInterface"
        };
        codeElementWriter.WriteCodeElement(declaration, writer);
        string result = tw.ToString();
        Assert.Contains(":", result);
    }

    [Fact]
    public void WritesImports()
    {
        ClassDeclaration declaration = parentClass.StartBlock;
        declaration.AddUsings(new()
        {
            Name = "Objects",
            Declaration = new()
            {
                Name = "system.util",
                IsExternal = true,
            }
        },
        new()
        {
            Name = "project.graph",
            Declaration = new()
            {
                Name = "Message",
            }
        });
        codeElementWriter.WriteCodeElement(declaration, writer);
        string result = tw.ToString();
        Assert.Contains("using", result);
        Assert.Contains("Project.Graph", result);
        Assert.Contains("System.Util", result);
    }

    [Theory]
    [InlineData(AccessModifier.Public)]
    [InlineData(AccessModifier.Internal)]
    public void WritesAccessModifier(AccessModifier accessModifier)
    {
        parentClass.Access = accessModifier;
        codeElementWriter.WriteCodeElement(parentClass.StartBlock, writer);
        string result = tw.ToString();
        Assert.Contains($"{accessModifier.ToString().ToLower()} partial class", result);
    }
}
