// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Demo.IntegrationTests.ApiClient.EnumReturn.IntegerNamespace;
using ReQuesty.Demo.IntegrationTests.ApiClient.EnumReturn.StringNamespace;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ReQuesty.Demo.IntegrationTests.ApiClient.EnumReturn
{
    /// <summary>
    /// Builds and executes requests for operations under \EnumReturn
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.5")]
    public partial class EnumReturnRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The integer property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.EnumReturn.IntegerNamespace.IntegerRequestBuilder Integer
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.EnumReturn.IntegerNamespace.IntegerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The string property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.EnumReturn.StringNamespace.StringRequestBuilder String
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.EnumReturn.StringNamespace.StringRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.EnumReturn.EnumReturnRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EnumReturnRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/EnumReturn", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.EnumReturn.EnumReturnRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EnumReturnRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/EnumReturn", rawUrl)
        {
        }
    }
}
#nullable restore
#pragma warning restore CS0618
