// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Demo.IntegrationTests.ApiClient.CollectionReturn.Objects.NullableNamespace;
using ReQuesty.Demo.IntegrationTests.ApiClient.Models;
using ReQuesty.Runtime.Abstractions.Serialization;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ReQuesty.Demo.IntegrationTests.ApiClient.CollectionReturn.Objects
{
    /// <summary>
    /// Builds and executes requests for operations under \CollectionReturn\objects
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.6")]
    public partial class ObjectsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The nullable property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.CollectionReturn.Objects.NullableNamespace.NullableRequestBuilder Nullable
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.CollectionReturn.Objects.NullableNamespace.NullableRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.CollectionReturn.Objects.ObjectsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ObjectsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/CollectionReturn/objects{?returnType*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.CollectionReturn.Objects.ObjectsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ObjectsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/CollectionReturn/objects{?returnType*}", rawUrl)
        {
        }
        /// <summary>
        /// Gets a list of SomeObject based on the specified return type.
        /// </summary>
        /// <returns>A List&lt;global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.SomeObject&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        public async Task<List<global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.SomeObject>?> GetAsync(Action<RequestConfiguration<global::ReQuesty.Demo.IntegrationTests.ApiClient.CollectionReturn.Objects.ObjectsRequestBuilder.ObjectsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.SomeObject>(requestInfo, global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.SomeObject.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Gets a list of SomeObject based on the specified return type.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ReQuesty.Demo.IntegrationTests.ApiClient.CollectionReturn.Objects.ObjectsRequestBuilder.ObjectsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.CollectionReturn.Objects.ObjectsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.CollectionReturn.Objects.ObjectsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::ReQuesty.Demo.IntegrationTests.ApiClient.CollectionReturn.Objects.ObjectsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Gets a list of SomeObject based on the specified return type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.6")]
        public partial class ObjectsRequestBuilderGetQueryParameters 
        {
            #pragma warning disable CS1591
            [QueryParameter("returnType")]
            public global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.ReturnType? ReturnType { get; set; } = default!;
            #pragma warning restore CS1591
        }
    }
}
#nullable restore
#pragma warning restore CS0618
