// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.StringId.Item;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.StringId
{
    /// <summary>
    /// Builds and executes requests for operations under \PathParameter\stringId
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.6")]
    public partial class StringIdRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.stringId.item collection</summary>
        /// <param name="position">The string ID.</param>
        /// <returns>A <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.StringId.Item.WithStringItemRequestBuilder"/></returns>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.StringId.Item.WithStringItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("stringId", position);
                return new global::ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.StringId.Item.WithStringItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.StringId.StringIdRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StringIdRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/PathParameter/stringId", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.StringId.StringIdRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StringIdRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/PathParameter/stringId", rawUrl)
        {
        }
    }
}
#nullable restore
#pragma warning restore CS0618
