// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Demo.IntegrationTests.ApiClient.ObjectReturn.SomeObject;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ReQuesty.Demo.IntegrationTests.ApiClient.ObjectReturn
{
    /// <summary>
    /// Builds and executes requests for operations under \ObjectReturn
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.5")]
    public partial class ObjectReturnRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The someObject property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.ObjectReturn.SomeObject.SomeObjectRequestBuilder SomeObject
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.ObjectReturn.SomeObject.SomeObjectRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.ObjectReturn.ObjectReturnRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ObjectReturnRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ObjectReturn", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.ObjectReturn.ObjectReturnRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ObjectReturnRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ObjectReturn", rawUrl)
        {
        }
    }
}
#nullable restore
#pragma warning restore CS0618
