// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Demo.IntegrationTests.ApiClient.QueryParameter.Bool;
using ReQuesty.Demo.IntegrationTests.ApiClient.QueryParameter.Filter;
using ReQuesty.Demo.IntegrationTests.ApiClient.QueryParameter.GuidNamespace;
using ReQuesty.Demo.IntegrationTests.ApiClient.QueryParameter.IntegerNamespace;
using ReQuesty.Demo.IntegrationTests.ApiClient.QueryParameter.StringNamespace;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ReQuesty.Demo.IntegrationTests.ApiClient.QueryParameter
{
    /// <summary>
    /// Builds and executes requests for operations under \QueryParameter
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.6")]
    public partial class QueryParameterRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The bool property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.QueryParameter.Bool.BoolRequestBuilder Bool
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.QueryParameter.Bool.BoolRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The filter property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.QueryParameter.Filter.FilterRequestBuilder Filter
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.QueryParameter.Filter.FilterRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The guid property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.QueryParameter.GuidNamespace.GuidRequestBuilder Guid
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.QueryParameter.GuidNamespace.GuidRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The integer property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.QueryParameter.IntegerNamespace.IntegerRequestBuilder Integer
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.QueryParameter.IntegerNamespace.IntegerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The string property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.QueryParameter.StringNamespace.StringRequestBuilder String
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.QueryParameter.StringNamespace.StringRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.QueryParameter.QueryParameterRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QueryParameterRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/QueryParameter", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.QueryParameter.QueryParameterRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QueryParameterRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/QueryParameter", rawUrl)
        {
        }
    }
}
#nullable restore
#pragma warning restore CS0618
