// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.GuidId;
using ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.IntegerId;
using ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.LongId;
using ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.StringId;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter
{
    /// <summary>
    /// Builds and executes requests for operations under \PathParameter
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.6")]
    public partial class PathParameterRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The guidId property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.GuidId.GuidIdRequestBuilder GuidId
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.GuidId.GuidIdRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The integerId property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.IntegerId.IntegerIdRequestBuilder IntegerId
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.IntegerId.IntegerIdRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The longId property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.LongId.LongIdRequestBuilder LongId
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.LongId.LongIdRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The stringId property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.StringId.StringIdRequestBuilder StringId
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.StringId.StringIdRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.PathParameterRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PathParameterRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/PathParameter", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.PathParameterRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PathParameterRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/PathParameter", rawUrl)
        {
        }
    }
}
#nullable restore
#pragma warning restore CS0618
