// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.IntegerId.Item;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.IntegerId
{
    /// <summary>
    /// Builds and executes requests for operations under \PathParameter\integerId
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.6")]
    public partial class IntegerIdRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.integerId.item collection</summary>
        /// <param name="position">The integer ID to determine the return type.</param>
        /// <returns>A <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.IntegerId.Item.WithIntegerItemRequestBuilder"/></returns>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.IntegerId.Item.WithIntegerItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("integerId", position);
                return new global::ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.IntegerId.Item.WithIntegerItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.IntegerId.IntegerIdRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IntegerIdRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/PathParameter/integerId", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.PathParameter.IntegerId.IntegerIdRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IntegerIdRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/PathParameter/integerId", rawUrl)
        {
        }
    }
}
#nullable restore
#pragma warning restore CS0618
