// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Demo.IntegrationTests.ApiClient.Models;
using ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.Long.NullableNamespace;
using ReQuesty.Runtime.Abstractions.Serialization;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.Long
{
    /// <summary>
    /// Builds and executes requests for operations under \PrimativeReturn\long
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.6")]
    public partial class LongRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The nullable property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.Long.NullableNamespace.NullableRequestBuilder Nullable
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.Long.NullableNamespace.NullableRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.Long.LongRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LongRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/PrimativeReturn/long{?returnType*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.Long.LongRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LongRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/PrimativeReturn/long{?returnType*}", rawUrl)
        {
        }
        /// <summary>
        /// Gets a long based on the specified return type.
        /// </summary>
        /// <returns>A <see cref="long"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        public async Task<long?> GetAsync(Action<RequestConfiguration<global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.Long.LongRequestBuilder.LongRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<long>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Gets a long based on the specified return type.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.Long.LongRequestBuilder.LongRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.Long.LongRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.Long.LongRequestBuilder WithUrl(string rawUrl)
        {
            return new global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.Long.LongRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Gets a long based on the specified return type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.6")]
        public partial class LongRequestBuilderGetQueryParameters 
        {
            #pragma warning disable CS1591
            [QueryParameter("returnType")]
            public global::ReQuesty.Demo.IntegrationTests.ApiClient.Models.ReturnType? ReturnType { get; set; } = default!;
            #pragma warning restore CS1591
        }
    }
}
#nullable restore
#pragma warning restore CS0618
