// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.GuidNamespace;
using ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.Int;
using ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.NullableGuid;
using ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.NullableInt;
using ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.NullableString;
using ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.StringNamespace;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn
{
    /// <summary>
    /// Builds and executes requests for operations under \PrimativeReturn
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.3")]
    public partial class PrimativeReturnRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The guid property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.GuidNamespace.GuidRequestBuilder Guid
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.GuidNamespace.GuidRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The int property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.Int.IntRequestBuilder Int
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.Int.IntRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The nullableGuid property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.NullableGuid.NullableGuidRequestBuilder NullableGuid
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.NullableGuid.NullableGuidRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The nullableInt property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.NullableInt.NullableIntRequestBuilder NullableInt
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.NullableInt.NullableIntRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The nullableString property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.NullableString.NullableStringRequestBuilder NullableString
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.NullableString.NullableStringRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The string property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.StringNamespace.StringRequestBuilder String
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.StringNamespace.StringRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.PrimativeReturnRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PrimativeReturnRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/PrimativeReturn", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.PrimativeReturnRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PrimativeReturnRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/PrimativeReturn", rawUrl)
        {
        }
    }
}
#nullable restore
#pragma warning restore CS0618
