// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.DoubleNamespace;
using ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.Float;
using ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.GuidNamespace;
using ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.IntegerNamespace;
using ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.StringNamespace;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn
{
    /// <summary>
    /// Builds and executes requests for operations under \PrimativeReturn
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.5")]
    public partial class PrimativeReturnRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The double property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.DoubleNamespace.DoubleRequestBuilder Double
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.DoubleNamespace.DoubleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The float property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.Float.FloatRequestBuilder Float
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.Float.FloatRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The guid property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.GuidNamespace.GuidRequestBuilder Guid
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.GuidNamespace.GuidRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The integer property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.IntegerNamespace.IntegerRequestBuilder Integer
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.IntegerNamespace.IntegerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The string property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.StringNamespace.StringRequestBuilder String
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.StringNamespace.StringRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.PrimativeReturnRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PrimativeReturnRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/PrimativeReturn", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.PrimativeReturn.PrimativeReturnRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PrimativeReturnRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/PrimativeReturn", rawUrl)
        {
        }
    }
}
#nullable restore
#pragma warning restore CS0618
