// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Demo.IntegrationTests.ApiClient.CollectionReturn.Integers;
using ReQuesty.Demo.IntegrationTests.ApiClient.CollectionReturn.Objects;
using ReQuesty.Demo.IntegrationTests.ApiClient.CollectionReturn.Strings;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ReQuesty.Demo.IntegrationTests.ApiClient.CollectionReturn
{
    /// <summary>
    /// Builds and executes requests for operations under \CollectionReturn
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.6")]
    public partial class CollectionReturnRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The integers property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.CollectionReturn.Integers.IntegersRequestBuilder Integers
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.CollectionReturn.Integers.IntegersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The objects property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.CollectionReturn.Objects.ObjectsRequestBuilder Objects
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.CollectionReturn.Objects.ObjectsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The strings property</summary>
        public global::ReQuesty.Demo.IntegrationTests.ApiClient.CollectionReturn.Strings.StringsRequestBuilder Strings
        {
            get => new global::ReQuesty.Demo.IntegrationTests.ApiClient.CollectionReturn.Strings.StringsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.CollectionReturn.CollectionReturnRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CollectionReturnRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/CollectionReturn", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ReQuesty.Demo.IntegrationTests.ApiClient.CollectionReturn.CollectionReturnRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CollectionReturnRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/CollectionReturn", rawUrl)
        {
        }
    }
}
#nullable restore
#pragma warning restore CS0618
